#!/usr/bin/env ruby

#%# family=auto
#%# capabilities=autoconf

name = 'piri_kueche'

if ARGV[0] == 'autoconf'
  puts 'yes'
  exit 0
elsif ARGV[0] == 'config'
  puts 'graph_title Bewegungsmelder'
  puts 'graph_vlabel events'
  puts 'graph_category Activity'
  puts "#{name}.label #{name}"
  exit 0
end

require 'time'   # always :)

count = 0
minutes_ago = Time.now - 300

logfile=`ls -tr /var/log/fhem/fhem* | tail -n1`
piri_lines = `tail -n 300 #{logfile.strip} |grep -a #{name}`
piri_lines.each do |l|
  count += 1 if Time.parse(l) >= minutes_ago
end
puts "#{name}.value #{count}"


