#!/bin/bash
 
#%# family=auto
#%# capabilities=autoconf
 
if [ "$1" = "autoconf" ]; then
 echo "yes"
 exit 0
fi

ZAEHLER="Gaszaehler"
LOG=`ls -tr /var/log/fhem/$ZAEHLER* | tail -n1`
RESULT=`tail -n 10 $LOG |grep current:|tail -n1|awk '{print $4}'`
 
if [ "$1" = "config" ] ; then
 echo 'graph_title Aktueller Gasverbrauch'
 echo 'graph_vlabel m^3'
 echo 'graph_info Leistung'
 echo 'graph_category Verbrauchsdaten'
 echo $ZAEHLER.label $ZAEHLER
 exit 0
fi
 
echo $ZAEHLER.value $RESULT
 
exit 0

