#!/bin/bash
 
#%# family=auto
#%# capabilities=autoconf
 
if [ "$1" = "autoconf" ]; then
 echo "yes"
 exit 0
fi

SENSOR="Temp_Dachboden"
LOG=`ls -tr /var/log/fhem/$SENSOR* | tail -n1`
RESULT=`tail -n 10 $LOG|grep temperature:|tail -n1|awk '{print $4}'`
 
if [ "$1" = "config" ] ; then
 echo 'graph_title Temperatur Dachboden'
 echo 'graph_vlabel Grad'
 echo 'graph_category Umweltdaten'
 echo $SENSOR.label $SENSOR
 exit 0
fi
 
echo $SENSOR.value $RESULT
 
exit 0

